"""FastAPI application for ReqEngineer."""

from __future__ import annotations

import json
import os
import urllib.error
import urllib.request
from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field, model_validator
from pathlib import Path

from typing import Literal

from .agent import AgentConfig, ConversationMessage, RequirementsAgent
from .store import InMemoryStore, StoredRequirement


store = InMemoryStore()
PROJECT_ROOT = Path(__file__).resolve().parent.parent
STATIC_DIR = PROJECT_ROOT / "static"


class RequirementsRequest(BaseModel):
    user_text: str | None = Field(None, min_length=1, description="Text generated by a user and sent by a backend.")
    idea: str | None = Field(None, min_length=1, description="Compatibility alias for user_text.")
    model: str | None = Field(None, description="OpenAI-compatible chat model name.")
    base_url: str | None = Field(None, description="OpenAI-compatible API base URL.")
    temperature: float | None = Field(None, ge=0, le=2, description="Sampling temperature.")
    timeout_seconds: int | None = Field(None, gt=0, description="Model request timeout.")
    review_iterations: int | None = Field(None, ge=0, le=2, description="Draft critique/revision passes.")

    @model_validator(mode="after")
    def validate_user_text(self) -> RequirementsRequest:
        if not (self.user_text or self.idea):
            raise ValueError("user_text is required.")
        return self


class Requirement(BaseModel):
    id: str
    name: str
    description: str
    priority: Literal["low", "medium", "high"]
    status: Literal["pending", "approved", "discarded"]


class AgentStep(BaseModel):
    name: str
    summary: str


class RequirementsResponse(BaseModel):
    requirements: list[Requirement]
    backend: str
    model: str
    agent_steps: list[AgentStep]


class SessionResponse(BaseModel):
    session_id: str


class ConversationResponse(BaseModel):
    conversation_id: str


class ChatMessageRequest(BaseModel):
    content: str = Field(..., min_length=1, description="User message from the chat UI.")
    model: str | None = Field(None, description="OpenAI-compatible chat model name.")
    base_url: str | None = Field(None, description="OpenAI-compatible API base URL.")
    temperature: float | None = Field(None, ge=0, le=2, description="Sampling temperature.")
    timeout_seconds: int | None = Field(None, gt=0, description="Model request timeout.")
    review_iterations: int | None = Field(None, ge=0, le=2, description="Draft critique/revision passes.")


class ChatMessageResponse(BaseModel):
    conversation_id: str
    message: dict[str, str]
    actions_performed: list[str]
    tool_calls: list[dict[str, object]] = Field(default_factory=list)
    draft_id: str | None = None
    requirements: list[Requirement] = Field(default_factory=list)
    agent_steps: list[AgentStep] = Field(default_factory=list)


class EmbeddingRequest(BaseModel):
    model: str | None = Field(None, description="OpenAI-compatible embedding model name.")
    base_url: str | None = Field(None, description="OpenAI-compatible API base URL.")
    timeout_seconds: int | None = Field(None, gt=0, description="Model request timeout.")


class EmbeddingResponse(BaseModel):
    requirement_id: str
    embedding_model: str
    dimensions: int
    stored: bool


app = FastAPI(
    title="ReqEngineer",
    version="0.1.0",
    description="AI agent API for turning rough product ideas into requirements drafts.",
)

app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


@app.get("/")
def index() -> FileResponse:
    return FileResponse(STATIC_DIR / "index.html")


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


def build_agent_config(
    model: str | None,
    base_url: str | None,
    temperature: float | None,
    timeout_seconds: int | None,
    review_iterations: int | None,
) -> AgentConfig:
    env_config = AgentConfig.from_env()
    return AgentConfig(
        base_url=base_url or env_config.base_url,
        model=model or env_config.model,
        temperature=temperature if temperature is not None else env_config.temperature,
        timeout_seconds=timeout_seconds or env_config.timeout_seconds,
        review_iterations=review_iterations
        if review_iterations is not None
        else env_config.review_iterations,
    )


def to_api_requirements(requirements: list[StoredRequirement]) -> list[Requirement]:
    return [
        Requirement(
            id=requirement.id,
            name=requirement.name,
            description=requirement.description,
            priority=requirement.priority,
            status=requirement.status,
        )
        for requirement in requirements
    ]


@app.post("/requirements", response_model=RequirementsResponse)
def create_requirements(request: RequirementsRequest) -> RequirementsResponse:
    config = build_agent_config(
        request.model,
        request.base_url,
        request.temperature,
        request.timeout_seconds,
        request.review_iterations,
    )
    agent = RequirementsAgent(config)

    try:
        result = agent.run(request.user_text or request.idea or "")
    except ValueError as error:
        raise HTTPException(status_code=422, detail=str(error)) from error
    except RuntimeError as error:
        raise HTTPException(status_code=502, detail=str(error)) from error

    stored_requirements = store.save_requirements(result.requirements)
    return RequirementsResponse(
        requirements=to_api_requirements(stored_requirements),
        backend="exo",
        model=agent.config.model or "",
        agent_steps=[AgentStep(**step.__dict__) for step in result.steps],
    )


@app.post("/sessions", response_model=SessionResponse)
def create_session() -> SessionResponse:
    session = store.create_session()
    return SessionResponse(session_id=session.id)


@app.post("/conversations", response_model=ConversationResponse)
def create_conversation() -> ConversationResponse:
    session = store.create_session()
    return ConversationResponse(conversation_id=session.id)


def conversation_text(messages: list[ConversationMessage]) -> str:
    return "\n".join(
        f"{message.role}: {message.content}"
        for message in messages
        if message.role in {"user", "assistant"}
    )


def has_prior_user_context(messages: list[ConversationMessage]) -> bool:
    prior_messages = messages[:-1]
    return any(message.role == "user" and message.content.strip() for message in prior_messages)


def explicitly_requests_requirements(content: str) -> bool:
    normalized = content.strip().lower()
    explicit_phrases = (
        "create the requirements",
        "create requirements",
        "generate the requirements",
        "generate requirements",
        "draft the requirements",
        "draft requirements",
        "make the requirements",
        "go ahead",
        "proceed",
        "yes, create",
        "yes create",
        "yes, go ahead",
        "that's it",
        "that is it",
        "looks good",
        "crear los requisitos",
        "genera los requisitos",
        "generar requisitos",
        "adelante",
        "procede",
    )
    return any(phrase in normalized for phrase in explicit_phrases)


def handle_conversation_message(
    conversation_id: str,
    request: ChatMessageRequest,
) -> ChatMessageResponse:
    session = store.get_session(conversation_id)
    if session is None:
        raise HTTPException(status_code=404, detail=f"Conversation not found: {conversation_id}")

    content = request.content.strip()
    if not content:
        raise HTTPException(status_code=422, detail="Message content cannot be empty.")

    config = build_agent_config(
        request.model,
        request.base_url,
        request.temperature,
        request.timeout_seconds,
        request.review_iterations,
    )
    agent = RequirementsAgent(config)

    store.append_message(
        conversation_id,
        ConversationMessage(role="user", content=content),
    )
    messages = store.get_messages(conversation_id)

    if explicitly_requests_requirements(content) and has_prior_user_context(messages):
        reply = "Sure, generating the requirements now."
        store.append_message(
            conversation_id,
            ConversationMessage(role="assistant", content=reply),
        )
        tool_calls = [
            {
                "name": "create_requirements_from_conversation",
                "arguments": {"source": "backend_explicit_request"},
            }
        ]
        transcript = conversation_text(store.get_messages(conversation_id))
        try:
            result = agent.run(transcript)
        except ValueError as error:
            raise HTTPException(status_code=422, detail=str(error)) from error
        except RuntimeError as error:
            raise HTTPException(status_code=502, detail=str(error)) from error

        draft, stored_requirements = store.create_draft(transcript, result.requirements)
        store.attach_draft_to_session(conversation_id, draft.id)
        store.append_message(
            conversation_id,
            ConversationMessage(role="tool", content=f"Created requirements draft {draft.id}."),
        )
        return ChatMessageResponse(
            conversation_id=conversation_id,
            message={"role": "assistant", "content": reply},
            actions_performed=["create_requirements_from_conversation"],
            tool_calls=tool_calls,
            draft_id=draft.id,
            requirements=to_api_requirements(stored_requirements),
            agent_steps=[
                AgentStep(
                    name="create_requirements_from_conversation",
                    summary="Executed backend tool directly from explicit user request.",
                ),
                *[AgentStep(**step.__dict__) for step in result.steps],
            ],
        )

    try:
        turn = agent.chat(messages)
    except ValueError as error:
        raise HTTPException(status_code=422, detail=str(error)) from error
    except RuntimeError as error:
        raise HTTPException(status_code=502, detail=str(error)) from error

    store.append_message(
        conversation_id,
        ConversationMessage(role="assistant", content=turn.reply),
    )

    tool_calls = [
        {"name": tool_call.name, "arguments": tool_call.arguments}
        for tool_call in turn.tool_calls
    ]
    if not tool_calls and explicitly_requests_requirements(content):
        tool_calls.append(
            {
                "name": "create_requirements_from_conversation",
                "arguments": {"source": "backend_explicit_request_fallback"},
            }
        )
    actions_performed: list[str] = []
    requirements: list[Requirement] = []
    draft_id: str | None = None
    agent_steps = [
        AgentStep(
            name="chat",
            summary=f"Generated chat reply with {len(turn.tool_calls)} tool call(s).",
        )
    ]

    for tool_call in tool_calls:
        if tool_call["name"] != "create_requirements_from_conversation":
            continue

        transcript = conversation_text(store.get_messages(conversation_id))
        try:
            result = agent.run(transcript)
        except ValueError as error:
            raise HTTPException(status_code=422, detail=str(error)) from error
        except RuntimeError as error:
            raise HTTPException(status_code=502, detail=str(error)) from error

        draft, stored_requirements = store.create_draft(transcript, result.requirements)
        store.attach_draft_to_session(conversation_id, draft.id)
        store.append_message(
            conversation_id,
            ConversationMessage(
                role="tool",
                content=f"Created requirements draft {draft.id}.",
            ),
        )
        actions_performed.append(tool_call["name"])
        draft_id = draft.id
        requirements = to_api_requirements(stored_requirements)
        agent_steps.extend(AgentStep(**step.__dict__) for step in result.steps)

    return ChatMessageResponse(
        conversation_id=conversation_id,
        message={"role": "assistant", "content": turn.reply},
        actions_performed=actions_performed,
        tool_calls=tool_calls,
        draft_id=draft_id,
        requirements=requirements,
        agent_steps=agent_steps,
    )


@app.post("/conversations/{conversation_id}/messages", response_model=ChatMessageResponse)
def create_conversation_message(
    conversation_id: str,
    request: ChatMessageRequest,
) -> ChatMessageResponse:
    return handle_conversation_message(conversation_id, request)


@app.post("/sessions/{session_id}/messages", response_model=ChatMessageResponse)
def create_session_message(session_id: str, request: ChatMessageRequest) -> ChatMessageResponse:
    return handle_conversation_message(session_id, request)


@app.post("/requirements/{req_id}/embedding", response_model=EmbeddingResponse)
def create_requirement_embedding(req_id: str, request: EmbeddingRequest) -> EmbeddingResponse:
    requirement = store.get_requirement(req_id)
    if requirement is None:
        raise HTTPException(status_code=404, detail=f"Requirement not found: {req_id}")

    model = request.model or os.getenv("EXO_EMBEDDING_MODEL")
    if not model:
        raise HTTPException(
            status_code=422,
            detail="Embedding model is required. Set EXO_EMBEDDING_MODEL or pass model.",
        )

    base_url = request.base_url or os.getenv("EXO_BASE_URL", AgentConfig.base_url)
    timeout_seconds = request.timeout_seconds or int(os.getenv("REQENGINEER_TIMEOUT_SECONDS", "300"))
    content = f"{requirement.name}\n\n{requirement.description}"

    payload = {"model": model, "input": content}
    embedding_request = urllib.request.Request(
        url=f"{base_url.rstrip('/')}/embeddings",
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(embedding_request, timeout=timeout_seconds) as response:
            body = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise HTTPException(status_code=502, detail=f"Embedding request failed with HTTP {error.code}: {detail}") from error
    except urllib.error.URLError as error:
        raise HTTPException(status_code=502, detail=f"Embedding request failed: {error.reason}") from error
    except TimeoutError as error:
        raise HTTPException(
            status_code=502,
            detail=f"Embedding request timed out after {timeout_seconds} seconds",
        ) from error

    try:
        vector = body["data"][0]["embedding"]
    except (KeyError, IndexError, TypeError) as error:
        raise HTTPException(status_code=502, detail=f"Unexpected embedding response: {body}") from error

    if not isinstance(vector, list) or not all(isinstance(value, int | float) for value in vector):
        raise HTTPException(status_code=502, detail="Embedding response did not include a numeric vector.")

    embedding = store.save_embedding(req_id, model, [float(value) for value in vector])
    return EmbeddingResponse(
        requirement_id=embedding.requirement_id,
        embedding_model=embedding.model,
        dimensions=embedding.dimensions,
        stored=True,
    )
